### ISSUE TITLE
Mod Downloader wont register in Yuzu 

### ISSUE THREAD

**Issue by Ahamil41** [amakvana/SwitchEmuModDownloader#38]
I followed the tutorial to add the mod downloader into yuzu, and when I ran it all the mods downloaded. However, when I open yuzu and right click there are no mods available for any games. All my paths/directories are set correctly so I am not sure what I am doing wrong. And as far as I can tell the mods are all compatible with the patches I have installed as well.
![Yuzu Mod Downloader 3_1_2024 2_55_30 AM](https://github.com/amakvana/YuzuModDownloader/assets/161813784/3ab2d855-e3f6-4aae-bc4a-dd3e2894fd97)

**Comment by amakvana** [comment]
Thanks for opening up the issue, could you fill in the Issue Template provided below to help identify what's going on:



**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop/Laptop (please complete the following information):**
 - OS: [e.g. Windows 11, Windows 10, Windows 7, etc.]
 - Yuzu Version [e.g. mainline 900, EA 2500]
 - Yuzu Standalone or Installed?
 - Game Title [e.g. Super Smash Bros. Ultimate]
 - Game Title ID [0xXXXXXXXXXXXXXXXX - found underneath the title in games list within Yuzu]
 - Path to `Mod Load Root` folder
 - Upload a copy of your `qt-config.ini`

**Additional context**
Add any other context about the problem here.

**Comment by amakvana** [comment]
This issue has been closed because there has been no response to our request for more information from the original author. With only the information that is currently in the issue, we don't have enough information to take action.

Please reach out if you have or find the answers we need so that we can investigate further.
